config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ActiveRecord::Base
  validates :name, presence: true
  end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }

      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :completed)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
%html
  %head
    %title Todo
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
  %body
    #flash-display
    - flash.each do |type, msg|
      %div
        = msg
    =yield

app/views/tasks/_form.html.haml
=form_for @task do |f|
  -if @task.errors.any?
    #error_explanation
      %h2="#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        -@task.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.label :name
    =f.text_field :name
  .field
    =f.label :completed
    =f.check_box :completed
  .actions
    =f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

=render 'form'

=link_to 'Show', @task
\|
=link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Tasks

%table
  %thead
    %tr
      %th Name
      %th Completed
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td=task.name
        %td=task.completed
        %td=link_to 'Show', task
        %td=link_to 'Edit', edit_task_path(task)
        %td=link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

=link_to 'Add a task', new_task_path

app/views/tasks/new.html.haml
%h1 Create a task

=render 'form'

=link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice=notice

%p
  %b Name:
  =@task.name
%p
  %b Completed:
  =@task.completed

=link_to 'Edit', edit_task_path(@task)
\|
=link_to 'Back', tasks_path